In [57]:
import numpy as np

In [3]:
# 1.1列表转换为矩阵
array = np.array([
    [1, 3, 5],
    [4, 6, 9]
])
# 其实就是把一个以列表为元素的列表转换了一下
print(array)

[[1 3 5]
 [4 6 9]]


In [4]:
print(array.ndim) # 打印row，其实就是原来的列表有多少个元素

2


In [5]:
print(array.shape) # dim(m, n)

(2, 3)


In [6]:
print(array.size) # size,2*3

6


In [7]:
# 2.1创建array
array = np.array([2, 23, 4], dtype = np.int32) # 表示数字类型是32位int
print(array)
print(array.dtype)

[ 2 23  4]
int32


In [9]:
array = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(array) # 多维数组的创建

[[1 2 3]
 [4 5 6]]


In [13]:
a = np.zeros((3, 4))
print(a) # 创造全0的多维数组
b = np.ones((3, 4), dtype = int)
print(b, b.dtype) # 全1多维数组，默认int是int64

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] int64


In [16]:
a = np.empty((3, 4))
print(a) # 这里其实不是0，是接近0的很小的数字

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
a = np.arange(10, 21, 2) # 用arange这个函数有点像列表生成式
print(a)
b = a.reshape((2, 3)) # 用reshape方法，可以自动生成相应形状的多维数组
print(b)

[10 12 14 16 18 20]
[[10 12 14]
 [16 18 20]]


In [19]:
a = np.linspace(1, 10, 20)
print(a) # 这里是生成了类似刻度的数据，1到10，20个，与前面的empty很相似，不是完全从1开始，而是一个很接近1的数字
b = a.reshape((4, 5))
print(b)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
[[ 1.          1.47368421  1.94736842  2.42105263  2.89473684]
 [ 3.36842105  3.84210526  4.31578947  4.78947368  5.26315789]
 [ 5.73684211  6.21052632  6.68421053  7.15789474  7.63157895]
 [ 8.10526316  8.57894737  9.05263158  9.52631579 10.        ]]


In [7]:
# 3.1numpy的基本运算
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.arange(4)
print(a, b)
print(a-b) # 和矩阵运算是非常相似的
print(a*b) # 乘法这个地方和矩阵乘法完全不一样，数组的乘法是对应元素直接相乘，有点像坐标的意思
print(a.dot(b)) # 这里就是将各个元素相乘然后相加，其实就是一个点乘的意思

[1 2 3 4] [0 1 2 3]
[1 1 1 1]
[ 0  2  6 12]
20


In [13]:
print(b**2) # 与普通运算相同的乘方操作
print(np.sin(b)) # 求sin函数
print(b < 2) # 这些逻辑符的运算和R里面几乎是一模一样的
print(a == b)

[0 1 4 9]
[0.         0.84147098 0.90929743 0.14112001]
[ True  True False False]
[False False False False]


In [19]:
# 一维的数组乘法，仍然是按照简单的对点相乘的方法来做的
# 而多维数组的乘法，就是按照矩阵乘法来计算了
a = np.array([
    [1, 2],
    [3, 4]
])
b = np.arange(4).reshape((2,2))
print(a)
print(b)
# 对于多维数组来说，不能直接像一维数组那样使用*来进行乘法运算
# 必须要使用dot方法
print(a*b) # 这样就会直接变成对应元素相乘
# 下面这两种才是按照矩阵乘法来计算的
print(a.dot(b)) 
print(np.dot(a, b))

[[1 2]
 [3 4]]
[[0 1]
 [2 3]]
[[ 0  2]
 [ 6 12]]
[[ 4  7]
 [ 8 15]]
[[ 4  7]
 [ 8 15]]


In [27]:
a = np.random.random((2,4)) # random也是np里面的一个module
# 这里和单纯的random module不一样，在np中的random输入的参数是定义了生成数组的shape
print(a) # 所以这里是一个2*4的矩阵
print(np.sum(a))
print(np.min(a))
print(np.max(a))
# 上述三个函数都能添加一个参数axis，axis = 1为按行寻找目标，axis = 0是按列寻找目标
print(np.min(a, axis = 0)) # 可以看到，这里出现了四个返回值，说明是按列寻找的
print(np.sum(a, axis = 1))

[[0.65193336 0.07833837 0.87774705 0.14666669]
 [0.65478461 0.7486479  0.9526649  0.04076186]]
4.151544741397214
0.04076185973036073
0.9526648989882135
[0.65193336 0.07833837 0.87774705 0.04076186]
[1.75468547 2.39685927]


In [37]:
a = np.arange(2, 14).reshape(3, 4)
print(a)
print(np.argmin(a)) # 打印最小元素的index，可以发现，python里面矩阵实质上还是一个list
print(np.argmax(a))
print(a.mean())
print(a.cumsum()) # 累加函数
print(np.diff(a)) # 这与累加函数不太一样，关注的是相邻两个元素的差值，可以发现输出元素降维了

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


In [41]:
C = np.array([[0,5,9],
              [4,0,10]])
print(C)
print(np.nonzero(C))
# nozero函数的结果比较抽象，返回的是两个数组，第一个数组表示row_index，第二个表示col_index
# 比如在此处，(array([0, 0, 1, 1]), array([1, 2, 0, 2]))
# 要前后两个结合起来看，组合起来才是一个非0元素的index
# 比如这里四个非零元素，组合一下坐标分别是(0,1)(0,2)(1,0)(1,2)

[[ 0  5  9]
 [ 4  0 10]]
(array([0, 0, 1, 1]), array([1, 2, 0, 2]))


In [49]:
a = np.arange(14, 2, -1).reshape(3, 4)
print(a)
print(np.sort(a)) # array里面也可以像list一样排序，但是要注意的是针对row进行排序

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [54]:
print(a.transpose()) # 转置也是有的
print(a.T) # 更方便更贴近数学的表达形式

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [56]:
np.clip(a, 5, 9)
# 感觉这也是一种切片操作

# clip(Array, Array_min, Array_max)
# 将Array_min < X < Array_max X表示矩阵A中的数，如果满足上述关系，则原数不变。
# 否则，如果X < Array_min，则将矩阵中X变为Array_min;
# 如果X > Array_max，则将矩阵中X变为Array_max.

array([[9, 9, 9, 9],
       [9, 9, 8, 7],
       [6, 5, 5, 5]])

In [12]:
# 4.1array索引和切片
import numpy as np
a = np.arange(3, 15)
print(a)
print(a[3])
b = a.reshape(3, 4)
print(b)
print(b[2])
print(b[0][2])
print(b[0, 2]) # 这两个东西是等价的，和R里面的逻辑基本上是完全一样的，除了python是0开始
print(b[1, 1:3])

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
5
5
[8 9]


In [15]:
for row in b:
    print(row) # 因为是通过list来构造的，所以只能实现打印rows
# 如果想要打印col，通过转置就可以实现了
for col in b.T:
    print(col)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [17]:
# 通过flatten这个迭代器，还可以实现多维转一维，其实这里的底层函数代码也不难写，确实是迭代器的原理
a = np.arange(3, 15).reshape(3, 4)
print(a)
b = a.flatten()
print(b)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [21]:
a = np.arange(0, 36).reshape(6, 6)
print(a)
a[(0, 1, 2), (1, 2, 3)] # 注意这种切片方式，本质上仍然是前面是行后面是列，但是通过列表的形式实现多对的一一对应
# 所以实际上在切片的时候向row/col index中传入一个变量也是可以的，只需要注意能对应上就好

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([ 1,  8, 15])

In [29]:
# 5.1array的合并操作
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.vstack((a, b)) # 看这两个合并函数的参数形式，其实可以发现，他们实际上是一个reshape函数
# 所以要求两个括号，其实是用来构造一个大的array
d = np.hstack((a, b))
print(c)
print(d)
print(np.shape(a), np.shape(b), np.shape(c)) # 可以发现，对一维array显示shape并不是按照dim来显示，而是只显示一个size
# 因为对于一维矩阵来说，python默认还认为他们是一个数组，一维的对象，自然也不会像矩阵一样显示dim信息

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
(3,) (3,) (2, 3)


In [38]:
# 由于python认为是一维的，所以a.T这种转置的方法也是不能用的，需要用其他的方法
a = np.array([1, 2, 3])
print(a)
print(a[np.newaxis, :])
print(np.shape(a), np.shape(a[np.newaxis, :])) # 可以发现，这里就被转化成了一个(1,3)的矩阵
# np.newaxis这个函数的意思就是，在它所在的位置创建一个新的维度（被视为矩阵的一个维度）
# 在这个例子中，就是在a的行的位置生成了一个维度，然后再用：把a所有的元素扔进去，这样就生成了一个(1,3)的矩阵
print(a[:, np.newaxis]) # 生成转置的列也是一样的道理

[1 2 3]
[[1 2 3]]
(3,) (1, 3)
[[1]
 [2]
 [3]]


In [56]:
a = np.arange(1, 4)
b = np.arange(4, 7)
c = np.hstack((a, b, a))
d = np.stack((c, c))
print(d, np.shape(d))
print(c, np.shape(c)) # 前面介绍了用stack来进行合并
a = a[np.newaxis, :]
b = b[np.newaxis, :]
c = np.concatenate((a, b), axis = 1)
print(c, np.shape(c))
# 目前感觉stack/concatenate这两个函数的差别并不是很大
# 唯一一个差别就是，使用concatenate来进行合并的时候需要先转换成矩阵

[[1 2 3 4 5 6 1 2 3]
 [1 2 3 4 5 6 1 2 3]] (2, 9)
[1 2 3 4 5 6 1 2 3] (9,)
[[1 2 3 4 5 6]] (1, 6)


In [59]:
# 6.1array的分隔
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [64]:
print(np.split(a, 2, axis = 1))
# np.split一共三个参数，前两个十分容易理解，第三个表示切割的方向，在这个例子中是1，表示横向从左到右去切割，等于是竖着来一刀
print(np.split(a, 2, axis = 1)[0]) # 再用索引切片就可以取出切出来的东西
print(np.split(a, 3, axis = 0)) # 这样就是竖向进行切割，横着来一刀
# 这里是平分切割的情况

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[[0 1]
 [4 5]
 [8 9]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [66]:
# 当打算不均匀的切割的时候，需要使用np.array_split
print(np.array_split(a, 2, axis = 0))

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [69]:
# 7.1arraycopy和=
a = np.arange(0, 4)
print(a)

[0 1 2 3]


In [72]:
b = a
print(b)
c = a
print(c)
d = b
print(d)
a[0] = 11
print(b, c, d) # 可以发现，当a的值发生改变之后，会产生连坐

[11  1  2  3]
[11  1  2  3]
[11  1  2  3]
[11  1  2  3] [11  1  2  3] [11  1  2  3]


In [74]:
d[1:3] = [22, 33]
print(a, b, c) # 后面的d改变，也会产生连坐

[11 22 33  3] [11 22 33  3] [11 22 33  3]


In [77]:
a = np.arange(0, 4)
b = np.copy(a)
a[0] = 19
print(a, b) # 用copy函数来赋值，就不会产生连坐效应

[19  1  2  3] [0 1 2 3]


In [80]:
# 8.1广播机制
# numpy数组间的基础运算是一对一，也就是a.shape == b.shape，但是当两者不一样的时候，就会自动触发广播机制，如下例子：
a = np.array([
    [1, 2, 3, 4],
    [1, 2, 3, 4],
    [1, 2, 3, 4],
    [1, 2, 3, 4]
])
b = np.array([1, 2, 3, 4])
print(a+b) # 按道理来说是不能相加的，但是python的处理方法就像是，直接把b重复了几遍然后相加了
# 当两个矩阵/一维数组的维度不一样时没，python会自动的将其重复补全，如果补全后能够吻合，那么就会进行相加
# 最极端的例子是(4,1)+(1,4)这两个矩阵居然能相加

[[2 4 6 8]
 [2 4 6 8]
 [2 4 6 8]
 [2 4 6 8]]


In [84]:
# 9.1常用函数
# np.bincount(x)
x = np.array([1, 2, 3, 3, 0, 1, 4])
np.bincount(x) # 这里其实是将x中的元素从小到大排序后，求他们出现的次数
w = np.array([0.3,0.5,0.7,0.6,0.1,-0.9,1])
np.bincount(x,weights=w) # 可以设置weights参数，其中元素个数与x中元素个数是对应的，并且相应的权重也是对应的
# 比如1这个元素，在x中[0][5]出现了，如果没设置weights那么得到的结果就是2
# 设置weights后，在weights[0][5]对应的是0.3和-0.9，那么1得到的结果就是0.3-0.9
np.bincount(x,weights=w,minlength=7) # 还可以设置minlength这个函数
# minlength会设定bincount结果的最小长度，这里只有5位，但是我们设置了7个，那么多出来的就会直接用0.进行补位

array([ 0.1, -0.6,  0.5,  1.3,  1. ,  0. ,  0. ])

In [88]:
# np.argmax()
x = [[1,3,3],
     [7,5,2]]
print(np.argmax(x)) # 要注意的是argmax返回的索引是按照从小到大排序过后的索引
x = np.array([1, 3, 2, 3, 0, 1, 0])
print(x.argmax()) # 如果重复碰到相同的max，就会返回第一个碰到的索引
x = [[1,7,3],
     [7,5,2]]
print(np.argmax(x)) # 结合一下，如果出现相同的最大数，则不会进行从小到大排序，直接返回第一个的索引，比如这里结果是1

3
1
1


In [90]:
# np.around，四舍五入函数
np.around([-0.6,1.2798,2.357,9.67,13], decimals=0) # 负数会自动进位取绝对值更大的
# 当decimals为非负数的时候，四舍五入的时候是包括5的
# 而当decimals为负数的时候
np.around([1,2,5,6,56], decimals=-1) # 表示看一位数决定是否进位，也就是个位数，此时不包括5
np.around([1,2,5,50,56,190], decimals=-2) # 看两位数，十位和各位，也就是十位个位必须超过50，进退位则是在百位进行

array([  0,   0,   0,   0, 100, 200])

In [94]:
# np.where
x = np.array([[1, 0],
       [2, -2],
     [-2, 1]])
print(x)

np.where(x > 0, x, 0)
# np.where一共三个参数，第一个是判断值，第二个是条件成立时返回的值，第三个则是条件不成立时返回的值
# np.where可以很方便的实现替换

[[ 1  0]
 [ 2 -2]
 [-2  1]]


array([[1, 0],
       [2, 0],
       [0, 1]])

In [96]:
# np.celi/floor
np.floor([-0.6,-1.4,-0.1,-1.8,0,1.4,1.7]) # 向左取整
np.ceil([1.2,1.5,1.8,2.1,2.0,-0.5,-0.6,-0.3]) # 取最小整数

array([ 2.,  2.,  2.,  3.,  2., -0., -0., -0.])